version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      GO111MODULE: "on"
      GOFLAGS: "-mod=vendor"

    working_directory: /go/src/github.com/rocketbitz/pool

    steps:
      - checkout

      - run:
          name: vendor
          command: go mod vendor

      - run:
          name: vet
          command: go vet ./...

      - run:
          name: build
          command: go build .

      - run:
          name: unit tests
          command: go test ./...
