version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.24.3
    environment:
      GOFLAGS: "-mod=vendor"
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Vendor modules
          command: go mod vendor
      - run:
          name: Vet
          command: go vet ./...
      - run:
          name: Build
          command: go build ./...
      - run:
          name: Unit tests
          command: go test -race ./...

workflows:
  build_and_test:
    jobs:
      - build
